require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '14.0'

target 'OCRMobileSDK' do
  use_react_native!(
    :path => "../node_modules/react-native",
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      :mac_catalyst_enabled => false
    )
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
      
      # RNPermissions Privacy Info dosyası eksikse oluştur
      if target.name == 'RNPermissions-RNPermissionsPrivacyInfo'
        privacy_file_path = File.join(installer.sandbox.root, '../node_modules/react-native-permissions/ios/PrivacyInfo.xcprivacy')
        unless File.exist?(privacy_file_path)
          File.open(privacy_file_path, 'w') do |f|
            f.write('<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
</dict>
</plist>')
          end
        end
      end
    end
  end
end
