name: Android CI

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Verify React Native installation
      run: |
        echo "Checking React Native installation..."
        ls -la node_modules/@react-native/ || echo "React Native not found in node_modules"
        if [ ! -d "node_modules/@react-native/gradle-plugin" ]; then
          echo "WARNING: React Native gradle plugin not found"
          echo "This is expected - build will use Maven Central dependencies"
        else
          echo "React Native gradle plugin found"
          ls -la node_modules/@react-native/gradle-plugin
        fi
      
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
      
    - name: Build with Gradle
      working-directory: ./android
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Run unit tests
      working-directory: ./android
      run: ./gradlew test --stacktrace
      continue-on-error: true
      
    - name: Generate test report
      if: always()
      working-directory: ./android
      run: ./gradlew jacocoTestReport
      continue-on-error: true
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: test-results
        path: android/app/build/test-results/
        
    - name: Upload coverage reports
      if: always()
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: coverage-reports
        path: android/app/build/reports/jacoco/
        
    - name: Comment test results on PR
      if: github.event_name == 'pull_request' && always()
      uses: EnricoMi/publish-unit-test-result-action@v2
      continue-on-error: true
      with:
        files: android/app/build/test-results/**/*.xml
        
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
      
    - name: Run lint
      working-directory: ./android
      run: ./gradlew lint
      continue-on-error: true
      
    - name: Upload lint results
      if: always()
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: lint-results
        path: android/app/build/reports/lint-results*.html
        
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: './android'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      continue-on-error: true
      with:
        sarif_file: 'trivy-results.sarif'
